# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2021-03-29 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribe',
            field=models.BooleanField(default=False, verbose_name='\u8ba2\u9605'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribe_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='\u8ba2\u9605\u65f6\u95f4'),
        ),
        migrations.RunSQL('update wechat_user set create_time=subscribe_time')
    ]
