# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2021-07-27 18:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_auto_20210329_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u6635\u79f0'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_wechat_user', to=settings.AUTH_USER_MODEL, verbose_name='\u7f51\u7ad9\u7528\u6237'),
        ),
    ]
